### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by saidsef** [saidsef/ml-classifier#42]
Service start error:

```python
Traceback (most recent call last):
  File "/app/classifier-ml.py", line 7, in <module>
    from flask import Flask, request, jsonify
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

```

**Comment by saidsef** [comment]
This appears to be an issue with `flask`, upgrading it to v2.1.0 should resolve the issue
